version: "{build}"
skip_branch_with_pr: true
skip_tags: true
build: off

environment:
  matrix:
    - nodejs_version: 8

# Install scripts. (runs after repo cloning)
install:
  # install Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install


# to run your custom scripts instead of automatic tests
test_script:
  - npm test

# to run your custom scripts instead of provider deployments
after_test:
  - node free_ss.js --cow > rc.txt
  - appveyor PushArtifact rc.txt
  - node free_ss.js > gui-config.json
  - appveyor PushArtifact gui-config.json
